name: Test

on:
  push:
    branches:
      - main-alt
  pull_request:
    branches:
      - main-alt

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install gotestfmt
        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Run tests
        run: |
          set -euo pipefail
          go test -race -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
